### ISSUE TITLE
[feature] add team color to !list

### ISSUE THREAD

**Issue by bakabo** [FoglyOgly/Meowth#105]
This feature will help trainers form groups remotely, quickly identify trainers at the raid based on their team color, and more.
For example,

Fill in the Trainer Names with their team color
!list
...Interested... [Yellow] Trainer1, Trainer2, Trainer3... , [Red] Trainer4, Trainer5..., [Blue] Trainer 6....
...On there way... [Yellow] T7
...Here... [Yellow] T8, [Red] T9, T10, T11, [Blue] T12, T13, T14, T15...

**Comment by FoglyOgly** [comment]
I don't actually think this is possible. The only thing I can think of that is close is if you mentioned the team roles, but that would ping a lot of users unnecessarily.

**Comment by bakabo** [comment]
got it thanks!
