### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by cb130felix** [FoglyOgly/Meowth#117]
Hi! Your bot has been very useful to our comunity. Do you plan to add multilanguage option to the bot? I would be very pleased to help translate it to portuguese(br).

**Comment by scragly** [comment]
The next major version will feature soon after it's release the ability to add community submitted translations for the public hosted bot. It should be expected to have a limited release in a few weeks or so and after tests and a bit of extra development should be ready to accept translations. Keep an eye out for announcements if you like by joining the support server, linked on the readme page, if you're not in it already.
