### ISSUE TITLE
Multi-server support

### ISSUE THREAD

**Issue by 6-lasers** [FoglyOgly/Meowth#12]
Need to abstract server-specific configuration settings:
- welcome_channel
- admin_role
- location data
- emoji names
- (should probably also do the raidchannel_dict to avoid unnecessary lookup overhead)

This means 1)storing them by server, probably using dictionary, and 2)providing some way of configuring them without modifying the code

**Comment by cris11368** [comment]
The bot works fine on multiple servers as long. In my case I disabled all but the raid specific features. No team roles, etc...
