### ISSUE TITLE
!timerset with extreme values

### ISSUE THREAD

**Issue by 6-lasers** [FoglyOgly/Meowth#13]
!timerset allows negative input (e.g. -1:00) which doesn't really make sense.
!timerset with extremely large numbers causes an exception and doesn't fail gracefully.

Need to come up with some sanity check for reasonable time bounds. (maybe 00:00 min, 24:00 max to future proof ourselves?)

**Comment by FoglyOgly** [comment]
Yeah, someone on a different server noticed that !timerset 0:00 seems to prevent it from accepting further !timerset commands as well.

**Comment by FoglyOgly** [comment]
Fixed! Just limited inputs to two hours for now and no negative values.
