### ISSUE TITLE
4 configure sessions....

### ISSUE THREAD

**Issue by CRAKD** [FoglyOgly/Meowth#155]
I have 4 configure sessions going on in dm at the same time. How do i wipe out all settings on Meowth and start over? Don’t see anything in the readme that allows that everything is save.

**Comment by doonce** [comment]
You can just send a "cancel" in DM and it will close out all configure sessions. Then just send !configure again. Make sure to complete the configuration before sending a !configure, or send a cancel if you don't finish it.
