### ISSUE TITLE
Not recognizing master

### ISSUE THREAD

**Issue by cris11368** [FoglyOgly/Meowth#159]
Like the post says, the bot isn't recognizing who the master is. Or maybe it is and just not responding correctly, I don't see any errors raised when attempting owner commands.

**Comment by doonce** [comment]
Make sure "master" in config.json is an int and not a str (remove the quotations).

**Comment by cris11368** [comment]
Thank you, very strange since I've had this config for quite a while and it worked just fine on the master branch. 🤔🤷‍♂️

**Comment by doonce** [comment]
You must not have updated things since we changed to discord.py 1.0.0a

**Comment by cris11368** [comment]
Yeah, btw, I believe the raid json needs an update. I'm terrible with pulls...
