### ISSUE TITLE
!wild and !raid commands fail if no trainer has previously done !want on that Pokemon

### ISSUE THREAD

**Issue by 6-lasers** [FoglyOgly/Meowth#2]
!wild and !raid commands fail if no trainer has previously done !want on that Pokemon. This could be avoided by creating the role if it didn't previously exist.

**Comment by FoglyOgly** [comment]
I added code to solve this just a bit ago. :)

**Comment by 6-lasers** [comment]
The corrected code has a typo--both the !wild and !raid commands are referring to the "entered_want" variable.
