### ISSUE TITLE
Is it possible to get friend info?

### ISSUE THREAD

**Issue by xswqaz** [FoglyOgly/Meowth#215]
I want to get freind info like LV, XP with contstant interval

**Comment by 6-lasers** [comment]
No, it’s unfortunately not possible to retrieve any ingame information through legitimate methods. So, this info cannot be obtained on an automated basis.

**Comment by xswqaz** [comment]
Thank you for reply
Is it unable to get friend info even bot account is one of them ?

**Comment by tyrope** [comment]
Possible? Probably.
Allowed by Niantic? No.

Given the second half of that answer, Fogly won't allow it either.

**Comment by scragly** [comment]
The above responses are correct, and our stances for TOS breaking is set in stone for Meowth. I'll close this issue to clear it from the list. Kind regards.
