### ISSUE TITLE
in launcher.py, time.sleep() have no parameters

### ISSUE THREAD

**Issue by hrenaud** [FoglyOgly/Meowth#216]
Hello, at line 64 the method time.sleep(t) needs a time value as parameters 

https://www.tutorialspoint.com/python/time_sleep.htm

regards

**Comment by scragly** [comment]
Thanks for the heads up, this was noted after your Issue by Fogly and was fixed in #217. 

Sorry for the delay in providing an actual update and closing this issue. Thanks!
