### ISSUE TITLE
In localized version, !counters is not working

### ISSUE THREAD

**Issue by hrenaud** [FoglyOgly/Meowth#218]
Hello,

Pokebatler use the english name of a pokemon to return data to Meowth.

## this is not working (in french) -> MAGICARPE
> https://fight.pokebattler.com/raids/defenders/MAGICARPE/levels/RAID_LEVEL_1/attackers/levels/30/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=OVERALL&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&randomAssistants=-1

## this is workging (in english) -> MAGIKARP
> https://fight.pokebattler.com/raids/defenders/MAGIKARP/levels/RAID_LEVEL_1/attackers/levels/30/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=OVERALL&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&randomAssistants=-1

Could you, only for this time, not using the translated name of the pokémon ?
And maybe, doing the same for the weather too.

Regards

**Comment by scragly** [comment]
Localised versions for Meowthv2 are considered alterations of our standard repository and as such is up to the implementer to maintain and adjust their version as needed to accommodate the changes they add. Unfortunately, we can't assign much priority to assisting with enhancing internationalisation support in Meowthv2 as we're working hard on other aspects that are considered higher priority at this stage.

We _are_ however actively working on the next major version of Meowth which will support contextual internationalisation in the live bot itself and in a much more robust way than would be possible with the current bot. 

Feel free to keep updated on the next version by popping into our discord support server if you would rather to not have such a hands-on experience with the hosting and maintenance itself.
