### ISSUE TITLE
Error when handling messages

### ISSUE THREAD

**Issue by crist074** [FoglyOgly/Meowth#29]
File ".\meowth.py", line 782, in on_message
    if message.channel in server_dict[message.server]['raidchannel_dict'] and server_dict[message.server]['raidchannel_dict'][message.channel]['active']:
KeyError: <discord.server.Server object at 0x000001EBB1A8D480>

**Comment by bjodasso** [comment]
I'm getting this too. First time trying to set this up.

**Comment by FoglyOgly** [comment]
That could happen if you are inviting the bot to your server before turning it on. I need to mention that in the readme.

**Comment by crist074** [comment]
I'm trying to run this locally and I execute the python script, the bot joins the server with the token, and then I try to run !configure. This is when the error happens.

**Comment by FoglyOgly** [comment]
Try kicking the bot from your server and reinviting it. Make sure the bot is running before you invite it.

**Comment by irrg** [comment]
@FoglyOgly when you're updating documentation, maybe also remove the mention of the avatar image; I had to go back to an older commit to find that. Thanks for all the work though!
