### ISSUE TITLE
:omw: and :here: create multiple entries for one trainer

### ISSUE THREAD

**Issue by 6-lasers** [FoglyOgly/Meowth#3]
:omw: and :here:, if invoked multiple times by the same trainer, create separate entries in the omw or waiting lists. It would be better if the bot checked if the trainer was already in the list and replaced the entry (or appended to it..? need to think about use cases).

**Comment by FoglyOgly** [comment]
Yeah. I was rushing to get the feature out and figured it was better to let them add more people if they forgot. But replacing their first entry in the list could work.

**Comment by 6-lasers** [comment]
I've resolved this issue in my branch. Your pull request #4 should fix it in master.
