### ISSUE TITLE
Allow specified users to modify gyms

### ISSUE THREAD

**Issue by TJReinert** [FoglyOgly/Meowth#329]
Are we able to make it so specified users can modify gyms? If effort is too high, could we consider lowering the permission required? Manage Guild seems like a high permissions. 

I'd like to delegate this task to a user without granting them that permission.

**Comment by Baviaan** [comment]
I don't think it's a high level permission at all. All it allows you is to rename the server (and set its location). If you cannot expect someone not to change that, why do you want to give them permission to wipe your entire database?

**Comment by TJReinert** [comment]
Holy cow, lets call this user error. I was thinking Manage Guild was 'Administrator' rather than 'Manage Server'. 

Not sure what I was thinking 15 days ago.
Thank you for the clarification and apologies for the time
