### ISSUE TITLE
Channels not deleted after raid ends

### ISSUE THREAD

**Issue by Kodarane** [FoglyOgly/Meowth#48]
I'm testing remotely hosted Meowth on my discord. Everything seems to work fine except that it does not delete the raid channels after the raid timer has run out.

**Comment by FoglyOgly** [comment]
I was not able to reproduce this issue with remotely hosted Meowth. The channel I had Meowth create was deleted five minutes after the expire time. Does Meowth send a message that the raid has expired? Double check that Meowth has the "manage channels" permission.

**Comment by Kodarane** [comment]
The permissions should be correct. There is no message about the raid ending. See screenshot. 

https://imgur.com/a/rKxGr

**Comment by FoglyOgly** [comment]
Have you reconfigured lately? This bug was widespread a couple of days ago
but the fix may require reconfiguring to take effect.

**Comment by Kodarane** [comment]
I did reconfigure and tested once again. Same issue. I have noticed that when I write !timer the time is given in 12 hour time format without any am/pm. Does not know if that could be the issue. I use timezone +2.

**Comment by FoglyOgly** [comment]
I'll try to update this whenever we figure out what's causing this issue. I don't think the am/pm causes the issue because the time is all handled in UTC anyway. The offset is only added when the timer is actually printed.

**Comment by Kodarane** [comment]
It does work now with the latest update.

**Comment by StrGazer61** [comment]
Same here, on my install, for what it's worth

in:    async def expire_channel(channel):

Its getting to here when the 5 minute post-raid expire timer expires but never makes it to the 2nd logger point:
 
logger.info("Expire_Channel - "+channel.name+": trying to delete")   
 await Meowth.delete_channel(channel)
logger.info("Expire_Channel - Channel Deleted - "+channel.name)
