### ISSUE TITLE
 localisation not working for Ex raids

### ISSUE THREAD

**Issue by williaaam33** [FoglyOgly/Meowth#68]
Line 2291 of Meowth.py causes the program to not recognize non english Ex raids, since it is looking for the phrase"Ex Raid" in english.
For example, we ( a french discord) can not get our invite recognized since on our invites it is written "Raid Ex"

**Comment by grogmanesquire** [comment]
my understanding is that currrently the only solution to this is to manually swap out in the code what string meowth looks for. I believe a future version will change to a system that is less language dependent. The current one also has an issue if the string is on 2 lines.
