### ISSUE TITLE
Type of pokemon does not appear

### ISSUE THREAD

**Issue by xavier1063** [FoglyOgly/Meowth#71]
Hello, 
When I report a !raidegg, I have not the picture of the Pokemon type.
I only have :
Croconaw :water:
Quilava :fire1: 
or other type including in emoji.rar directory.

Have I made a mistake in config ?

Best regards,
Xavier

**Comment by FoglyOgly** [comment]
It's trying to use the external emoji from the hosted version. In
config.json, just change the strings to :water: etc.

**Comment by xavier1063** [comment]
Thank you for the answer.
So in config.json, there is : "water"    : "<:water:350686939571290112>"
So, to fix, I have to write :   "water"    : "<:water:>"

Is it correct ?
Emoji.rar file has to be unzipped ?

Best regards,
Xavier

**Comment by Kodarane** [comment]
Unzip Emoji.rar and upload the emojis to you Discord server

**Comment by xavier1063** [comment]
Thank you.

But what about the command line in config.json ?

In config.json, there is : "water" : "<:water:350686939571290112>"

So, to fix, I have to write : "water" : "<:water:>"

Is it ok ?

Best regards
Xavier.

**Comment by Kodarane** [comment]
Yes, but I think its kind of buggy. I had to change every time for it to work on any of them. Took a long time before i realized. Also the teams does not work for me.

**Comment by xavier1063** [comment]
In which directory the program checks the pictures of emoji ?

In get_type(), you use parse_emoji().
In parse_emoji(), you have :
emoji = discord.utils.get(server.emojis, name=emoji_string.strip(':')) 

What is server.emojis please ?

Best regards.
Xavier

**Comment by doonce** [comment]
You need to upload the emoji to your discord server by going to Server Settings --> Emoji. In config.json, remove the numbers so that it is just ":emoji:" with no <> or numbers for all emoji.

Example:
`"//": "Emoji for team assignments",
"team_dict": {"mystic": ":mystic:", "valor": ":valor:", "instinct": ":instinct:"},

"//": "Emoji for raid organization",
"omw_id": ":omw:",
"here_id": ":here:",

"//": "Emoji for Pokemon types.",
"type_id_dict": {
    "normal"   : ":normal:",
    "fire"     : ":fire1:",
    "water"    : ":water:",
    "electric" : ":electric:",
    "grass"    : ":grass:",
    "ice"      : ":ice:",
    "fighting" : ":fighting:",
    "poison"   : ":poison:",
    "ground"   : ":ground:",
    "flying"   : ":flying:",
    "psychic"  : ":psychic:",
    "bug"      : ":bug1:",
    "rock"     : ":rock:",
    "ghost"    : ":ghost1:",
    "dragon"   : ":dragon:",
    "dark"     : ":dark:",
    "steel"    : ":steel:",
    "fairy"    : ":fairy:"
}`
